apiVersion: v1
kind: Service
metadata:
  name: wh-service
  labels:
    app: wh
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 32080
  selector:
    matchLabels:
      app: wh
